<?php

namespace web3tc\EchangeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContratEtudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratEtudeRepository extends EntityRepository
{
}
